package com.kochetkov.archiver.solve

import java.io.*
import java.util.*

/*
 * Reference arithmetic coding
 * Copyright (c) Project Nayuki
 * 
 * https://www.nayuki.io/page/reference-arithmetic-coding
 * https://github.com/nayuki/Reference-arithmetic-coding
 */ /**
 * Decompression application using prediction by partial matching (PPM) with arithmetic coding.
 *
 * Usage: java PpmDecompress InputFile OutputFile
 *
 * This decompresses files generated by the "PpmCompress" application.
 */
object PpmDecompress {
    // Must be at least -1 and match PpmCompress. Warning: Exponential memory usage at O(257^n).
    private const val MODEL_ORDER = 3
    @Throws(IOException::class)
    @JvmStatic
    fun main(args: Array<String>) {
        // Handle command line arguments
        if (args.size != 2) {
            System.err.println("Usage: java PpmDecompress InputFile OutputFile")
            System.exit(1)
            return
        }
        val inputFile = File(args[0])
        val outputFile = File(args[1])
        BitInputStream(BufferedInputStream(FileInputStream(inputFile))).use { `in` -> BufferedOutputStream(FileOutputStream(outputFile)).use { out -> decompress(`in`, out) } }
    }

    // To allow unit testing, this method is package-private instead of private.
    @Throws(IOException::class)
    fun decompress(`in`: BitInputStream?, out: OutputStream) {
        // Set up decoder and model. In this PPM model, symbol 256 represents EOF;
        // its frequency is 1 in the order -1 context but its frequency
        // is 0 in all other contexts (which have non-negative order).
        val dec = ArithmeticDecoder(32, `in`!!)
        val model = PpmModel(MODEL_ORDER, 257, 256)
        var history = IntArray(0)
        while (true) {
            // Decode and write one byte
            val symbol = decodeSymbol(dec, model, history)
            if (symbol == 256) // EOF symbol
                break
            out.write(symbol)
            model.incrementContexts(history, symbol)
            if (model.modelOrder >= 1) {
                // Prepend current symbol, dropping oldest symbol if necessary
                if (history.size < model.modelOrder) history = Arrays.copyOf(history, history.size + 1)
                System.arraycopy(history, 0, history, 1, history.size - 1)
                history[0] = symbol
            }
        }
    }

    @Throws(IOException::class)
    private fun decodeSymbol(dec: ArithmeticDecoder, model: PpmModel, history: IntArray): Int {
        // Try to use highest order context that exists based on the history suffix. When symbol 256
        // is consumed at a context at any non-negative order, it means "escape to the next lower order
        // with non-empty context". When symbol 256 is consumed at the order -1 context, it means "EOF".
        outer@ for (order in history.size downTo 0) {
            var ctx = model.rootContext
            for (i in 0 until order) {
                if (ctx!!.subcontexts == null) throw AssertionError()
                ctx = ctx.subcontexts!![history[i]]
                if (ctx == null) continue@outer
            }
            val symbol = dec.read(ctx!!.frequencies)
            if (symbol < 256) return symbol
            // Else we read the context escape symbol, so continue decrementing the order
        }
        // Logic for order = -1
        return dec.read(model.orderMinus1Freqs)
    }
}